# Generated by Django 5.1.4 on 2025-01-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='sphere_registration',
        ),
    ]
