# Generated by Django 5.1.4 on 2025-02-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0005_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='sphere_message',
        ),
    ]
