# Generated by Django 5.1.4 on 2025-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0006_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
